//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.07 at 01:05:01 AM BST 
//


package com.justdelivery.api.model.google.geocoding;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="results">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="address_components" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="long_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="short_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="types" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="formatted_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="geometry">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="bounds">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="northeast">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                 &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="southwest">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                 &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="location">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="location_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="viewport">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="northeast">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                 &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="southwest">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                 &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="types" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "results",
    "status"
})
@XmlRootElement(name = "GeocodingResponse")
public class GeocodingResponse {

    @XmlElement(required = true)
    protected GeocodingResponse.Results results;
    @XmlElement(required = true)
    protected String status;

    /**
     * Gets the value of the results property.
     * 
     * @return
     *     possible object is
     *     {@link GeocodingResponse.Results }
     *     
     */
    public GeocodingResponse.Results getResults() {
        return results;
    }

    /**
     * Sets the value of the results property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeocodingResponse.Results }
     *     
     */
    public void setResults(GeocodingResponse.Results value) {
        this.results = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="address_components" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="long_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="short_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="types" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="formatted_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="geometry">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="bounds">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="northeast">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                       &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="southwest">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                       &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="location">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="location_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="viewport">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="northeast">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                       &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="southwest">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                       &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="types" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "addressComponents",
        "formattedAddress",
        "geometry",
        "types"
    })
    public static class Results {

        @XmlElement(name = "address_components")
        protected List<GeocodingResponse.Results.AddressComponents> addressComponents;
        @XmlElement(name = "formatted_address", required = true)
        protected String formattedAddress;
        @XmlElement(required = true)
        protected GeocodingResponse.Results.Geometry geometry;
        @XmlElement(required = true)
        protected String types;

        /**
         * Gets the value of the addressComponents property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the addressComponents property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAddressComponents().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GeocodingResponse.Results.AddressComponents }
         * 
         * 
         */
        public List<GeocodingResponse.Results.AddressComponents> getAddressComponents() {
            if (addressComponents == null) {
                addressComponents = new ArrayList<GeocodingResponse.Results.AddressComponents>();
            }
            return this.addressComponents;
        }

        /**
         * Gets the value of the formattedAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormattedAddress() {
            return formattedAddress;
        }

        /**
         * Sets the value of the formattedAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormattedAddress(String value) {
            this.formattedAddress = value;
        }

        /**
         * Gets the value of the geometry property.
         * 
         * @return
         *     possible object is
         *     {@link GeocodingResponse.Results.Geometry }
         *     
         */
        public GeocodingResponse.Results.Geometry getGeometry() {
            return geometry;
        }

        /**
         * Sets the value of the geometry property.
         * 
         * @param value
         *     allowed object is
         *     {@link GeocodingResponse.Results.Geometry }
         *     
         */
        public void setGeometry(GeocodingResponse.Results.Geometry value) {
            this.geometry = value;
        }

        /**
         * Gets the value of the types property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypes() {
            return types;
        }

        /**
         * Sets the value of the types property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypes(String value) {
            this.types = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="long_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="short_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="types" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "longName",
            "shortName",
            "types"
        })
        public static class AddressComponents {

            @XmlElement(name = "long_name", required = true)
            protected String longName;
            @XmlElement(name = "short_name", required = true)
            protected String shortName;
            protected List<String> types;

            /**
             * Gets the value of the longName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLongName() {
                return longName;
            }

            /**
             * Sets the value of the longName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLongName(String value) {
                this.longName = value;
            }

            /**
             * Gets the value of the shortName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShortName() {
                return shortName;
            }

            /**
             * Sets the value of the shortName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShortName(String value) {
                this.shortName = value;
            }

            /**
             * Gets the value of the types property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the types property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTypes().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getTypes() {
                if (types == null) {
                    types = new ArrayList<String>();
                }
                return this.types;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="bounds">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="northeast">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                             &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="southwest">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                             &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="location">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="location_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="viewport">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="northeast">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                             &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="southwest">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                             &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bounds",
            "location",
            "locationType",
            "viewport"
        })
        public static class Geometry {

            @XmlElement(required = true)
            protected GeocodingResponse.Results.Geometry.Bounds bounds;
            @XmlElement(required = true)
            protected GeocodingResponse.Results.Geometry.Location location;
            @XmlElement(name = "location_type", required = true)
            protected String locationType;
            @XmlElement(required = true)
            protected GeocodingResponse.Results.Geometry.Viewport viewport;

            /**
             * Gets the value of the bounds property.
             * 
             * @return
             *     possible object is
             *     {@link GeocodingResponse.Results.Geometry.Bounds }
             *     
             */
            public GeocodingResponse.Results.Geometry.Bounds getBounds() {
                return bounds;
            }

            /**
             * Sets the value of the bounds property.
             * 
             * @param value
             *     allowed object is
             *     {@link GeocodingResponse.Results.Geometry.Bounds }
             *     
             */
            public void setBounds(GeocodingResponse.Results.Geometry.Bounds value) {
                this.bounds = value;
            }

            /**
             * Gets the value of the location property.
             * 
             * @return
             *     possible object is
             *     {@link GeocodingResponse.Results.Geometry.Location }
             *     
             */
            public GeocodingResponse.Results.Geometry.Location getLocation() {
                return location;
            }

            /**
             * Sets the value of the location property.
             * 
             * @param value
             *     allowed object is
             *     {@link GeocodingResponse.Results.Geometry.Location }
             *     
             */
            public void setLocation(GeocodingResponse.Results.Geometry.Location value) {
                this.location = value;
            }

            /**
             * Gets the value of the locationType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocationType() {
                return locationType;
            }

            /**
             * Sets the value of the locationType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocationType(String value) {
                this.locationType = value;
            }

            /**
             * Gets the value of the viewport property.
             * 
             * @return
             *     possible object is
             *     {@link GeocodingResponse.Results.Geometry.Viewport }
             *     
             */
            public GeocodingResponse.Results.Geometry.Viewport getViewport() {
                return viewport;
            }

            /**
             * Sets the value of the viewport property.
             * 
             * @param value
             *     allowed object is
             *     {@link GeocodingResponse.Results.Geometry.Viewport }
             *     
             */
            public void setViewport(GeocodingResponse.Results.Geometry.Viewport value) {
                this.viewport = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="northeast">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                   &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="southwest">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                   &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "northeast",
                "southwest"
            })
            public static class Bounds {

                @XmlElement(required = true)
                protected GeocodingResponse.Results.Geometry.Bounds.Northeast northeast;
                @XmlElement(required = true)
                protected GeocodingResponse.Results.Geometry.Bounds.Southwest southwest;

                /**
                 * Gets the value of the northeast property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link GeocodingResponse.Results.Geometry.Bounds.Northeast }
                 *     
                 */
                public GeocodingResponse.Results.Geometry.Bounds.Northeast getNortheast() {
                    return northeast;
                }

                /**
                 * Sets the value of the northeast property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link GeocodingResponse.Results.Geometry.Bounds.Northeast }
                 *     
                 */
                public void setNortheast(GeocodingResponse.Results.Geometry.Bounds.Northeast value) {
                    this.northeast = value;
                }

                /**
                 * Gets the value of the southwest property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link GeocodingResponse.Results.Geometry.Bounds.Southwest }
                 *     
                 */
                public GeocodingResponse.Results.Geometry.Bounds.Southwest getSouthwest() {
                    return southwest;
                }

                /**
                 * Sets the value of the southwest property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link GeocodingResponse.Results.Geometry.Bounds.Southwest }
                 *     
                 */
                public void setSouthwest(GeocodingResponse.Results.Geometry.Bounds.Southwest value) {
                    this.southwest = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *         &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "lat",
                    "lng"
                })
                public static class Northeast {

                    protected float lat;
                    protected float lng;

                    /**
                     * Gets the value of the lat property.
                     * 
                     */
                    public float getLat() {
                        return lat;
                    }

                    /**
                     * Sets the value of the lat property.
                     * 
                     */
                    public void setLat(float value) {
                        this.lat = value;
                    }

                    /**
                     * Gets the value of the lng property.
                     * 
                     */
                    public float getLng() {
                        return lng;
                    }

                    /**
                     * Sets the value of the lng property.
                     * 
                     */
                    public void setLng(float value) {
                        this.lng = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *         &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "lat",
                    "lng"
                })
                public static class Southwest {

                    protected float lat;
                    protected float lng;

                    /**
                     * Gets the value of the lat property.
                     * 
                     */
                    public float getLat() {
                        return lat;
                    }

                    /**
                     * Sets the value of the lat property.
                     * 
                     */
                    public void setLat(float value) {
                        this.lat = value;
                    }

                    /**
                     * Gets the value of the lng property.
                     * 
                     */
                    public float getLng() {
                        return lng;
                    }

                    /**
                     * Sets the value of the lng property.
                     * 
                     */
                    public void setLng(float value) {
                        this.lng = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "lat",
                "lng"
            })
            public static class Location {

                protected float lat;
                protected float lng;

                /**
                 * Gets the value of the lat property.
                 * 
                 */
                public float getLat() {
                    return lat;
                }

                /**
                 * Sets the value of the lat property.
                 * 
                 */
                public void setLat(float value) {
                    this.lat = value;
                }

                /**
                 * Gets the value of the lng property.
                 * 
                 */
                public float getLng() {
                    return lng;
                }

                /**
                 * Sets the value of the lng property.
                 * 
                 */
                public void setLng(float value) {
                    this.lng = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="northeast">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                   &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="southwest">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                   &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "northeast",
                "southwest"
            })
            public static class Viewport {

                @XmlElement(required = true)
                protected GeocodingResponse.Results.Geometry.Viewport.Northeast northeast;
                @XmlElement(required = true)
                protected GeocodingResponse.Results.Geometry.Viewport.Southwest southwest;

                /**
                 * Gets the value of the northeast property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link GeocodingResponse.Results.Geometry.Viewport.Northeast }
                 *     
                 */
                public GeocodingResponse.Results.Geometry.Viewport.Northeast getNortheast() {
                    return northeast;
                }

                /**
                 * Sets the value of the northeast property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link GeocodingResponse.Results.Geometry.Viewport.Northeast }
                 *     
                 */
                public void setNortheast(GeocodingResponse.Results.Geometry.Viewport.Northeast value) {
                    this.northeast = value;
                }

                /**
                 * Gets the value of the southwest property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link GeocodingResponse.Results.Geometry.Viewport.Southwest }
                 *     
                 */
                public GeocodingResponse.Results.Geometry.Viewport.Southwest getSouthwest() {
                    return southwest;
                }

                /**
                 * Sets the value of the southwest property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link GeocodingResponse.Results.Geometry.Viewport.Southwest }
                 *     
                 */
                public void setSouthwest(GeocodingResponse.Results.Geometry.Viewport.Southwest value) {
                    this.southwest = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *         &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "lat",
                    "lng"
                })
                public static class Northeast {

                    protected float lat;
                    protected float lng;

                    /**
                     * Gets the value of the lat property.
                     * 
                     */
                    public float getLat() {
                        return lat;
                    }

                    /**
                     * Sets the value of the lat property.
                     * 
                     */
                    public void setLat(float value) {
                        this.lat = value;
                    }

                    /**
                     * Gets the value of the lng property.
                     * 
                     */
                    public float getLng() {
                        return lng;
                    }

                    /**
                     * Sets the value of the lng property.
                     * 
                     */
                    public void setLng(float value) {
                        this.lng = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *         &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "lat",
                    "lng"
                })
                public static class Southwest {

                    protected float lat;
                    protected float lng;

                    /**
                     * Gets the value of the lat property.
                     * 
                     */
                    public float getLat() {
                        return lat;
                    }

                    /**
                     * Sets the value of the lat property.
                     * 
                     */
                    public void setLat(float value) {
                        this.lat = value;
                    }

                    /**
                     * Gets the value of the lng property.
                     * 
                     */
                    public float getLng() {
                        return lng;
                    }

                    /**
                     * Sets the value of the lng property.
                     * 
                     */
                    public void setLng(float value) {
                        this.lng = value;
                    }

                }

            }

        }

    }

}
