//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.07 at 01:05:01 AM BST 
//


package com.justdelivery.api.model.google.geocoding;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.justdelivery.api.model.google.geocoding package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.justdelivery.api.model.google.geocoding
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GeocodingResponse.Results.Geometry }
     * 
     */
    public GeocodingResponse.Results.Geometry createGeocodingResponseResultsGeometry() {
        return new GeocodingResponse.Results.Geometry();
    }

    /**
     * Create an instance of {@link GeocodingResponse }
     * 
     */
    public GeocodingResponse createGeocodingResponse() {
        return new GeocodingResponse();
    }

    /**
     * Create an instance of {@link GeocodingResponse.Results.Geometry.Bounds.Southwest }
     * 
     */
    public GeocodingResponse.Results.Geometry.Bounds.Southwest createGeocodingResponseResultsGeometryBoundsSouthwest() {
        return new GeocodingResponse.Results.Geometry.Bounds.Southwest();
    }

    /**
     * Create an instance of {@link GeocodingResponse.Results.Geometry.Viewport.Southwest }
     * 
     */
    public GeocodingResponse.Results.Geometry.Viewport.Southwest createGeocodingResponseResultsGeometryViewportSouthwest() {
        return new GeocodingResponse.Results.Geometry.Viewport.Southwest();
    }

    /**
     * Create an instance of {@link GeocodingResponse.Results.Geometry.Viewport }
     * 
     */
    public GeocodingResponse.Results.Geometry.Viewport createGeocodingResponseResultsGeometryViewport() {
        return new GeocodingResponse.Results.Geometry.Viewport();
    }

    /**
     * Create an instance of {@link GeocodingResponse.Results.Geometry.Location }
     * 
     */
    public GeocodingResponse.Results.Geometry.Location createGeocodingResponseResultsGeometryLocation() {
        return new GeocodingResponse.Results.Geometry.Location();
    }

    /**
     * Create an instance of {@link GeocodingResponse.Results.Geometry.Viewport.Northeast }
     * 
     */
    public GeocodingResponse.Results.Geometry.Viewport.Northeast createGeocodingResponseResultsGeometryViewportNortheast() {
        return new GeocodingResponse.Results.Geometry.Viewport.Northeast();
    }

    /**
     * Create an instance of {@link GeocodingResponse.Results.Geometry.Bounds.Northeast }
     * 
     */
    public GeocodingResponse.Results.Geometry.Bounds.Northeast createGeocodingResponseResultsGeometryBoundsNortheast() {
        return new GeocodingResponse.Results.Geometry.Bounds.Northeast();
    }

    /**
     * Create an instance of {@link GeocodingResponse.Results }
     * 
     */
    public GeocodingResponse.Results createGeocodingResponseResults() {
        return new GeocodingResponse.Results();
    }

    /**
     * Create an instance of {@link GeocodingResponse.Results.Geometry.Bounds }
     * 
     */
    public GeocodingResponse.Results.Geometry.Bounds createGeocodingResponseResultsGeometryBounds() {
        return new GeocodingResponse.Results.Geometry.Bounds();
    }

    /**
     * Create an instance of {@link GeocodingResponse.Results.AddressComponents }
     * 
     */
    public GeocodingResponse.Results.AddressComponents createGeocodingResponseResultsAddressComponents() {
        return new GeocodingResponse.Results.AddressComponents();
    }

}
